name: publish
on:
  push:
    branches:
      - master

env:
  HEX_API_KEY: ${{ secrets.HEX_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.0.2
          elixir-version: 1.13.1

      - run: mix deps.get
      - run: mix test
      - run: mix hex.organization auth superlistapp --key ${{ secrets.HEX_TOKEN }}
      - run: mix hex.publish --organization superlistapp --yes
